language: ruby
rvm:
  - 2.3.0
services:
  - postgresql
env:
  RAILS_ENV=test SECRET_KEY_BASE='$(bundle exec rake secret)'
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bin/rake db:migrate RAILS_ENV=test
