# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eee62df8f48fe5a69b8b39d98e49776a2c8056e776ba9a9af82e3d3d78440b1703e0c635af9720e896a550d4e69727ef5561a69caefa36ae9a915863d6200f3
  SORCERY_TWITTER_KEY: HgUuqMwllMwztx9pIffp5lo0d
  SORCERY_TWITTER_SECRET: EiR0OztHEmr6re84tvkdZEUvTsQn4oWBcwGEQITnuirkSrnM7p
  SORCERY_TWITTER_CALLBACK_URL: http://0.0.0.0:3000/home/oauth/callback?provider=twitter
  S3_KEY: AKIAIXBUGO5USUHDZ5QA
  S3_SECRET: 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

  # Facebook
  SORCERY_FACEBOOK_KEY: 529658323890693
  SORCERY_FACEBOOK_SECRET: f090f2c82711db000c61128334479df1
  SORCERY_FACEBOOK_CALLBACK_URL: http://0.0.0.0:3000/home/oauth/callback?provider=facebook

  # Github
  SORCERY_GITHUB_KEY: edc545fd609bb86568eb
  SORCERY_GITHUB_SECRET: 91844cf97fd03068a7ae10efb054a346c28cf442
  SORCERY_GITHUB_CALLBACK_URL: http://0.0.0.0:3000/home/oauth/callback?provider=github

test:
  secret_key_base: 1d36f080492e96fe46a069917c18d67f631943abae9327ef52182d6636a465c9c36a75e05ce12eae3004602e5752dbcbe29eacb6d06e2b219132e055b575a4a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
